const russianVocabulary = [
  { english: "in / at", russian: "в" },
  { english: "not", russian: "не" },
  { english: "he", russian: "он" },
  { english: "on / it / at / to", russian: "на" },
  { english: "I", russian: "я" },
  { english: "what / that / why", russian: "что" },
  { english: "that", russian: "тот" },
  { english: "to be", russian: "быть" },
  { english: "with / and / from / of", russian: "с" },
  { english: "while / and / but", russian: "а" },
  { english: "all / everything", russian: "весь" },
  { english: "that / this / it", russian: "это" },
  { english: "how / what / as / like", russian: "как" },
  { english: "she", russian: "она" },
  { english: "on / along / by", russian: "по" },
  { english: "but", russian: "но" },
  { english: "they", russian: "они" },
  { english: "to / for / by", russian: "к" },
  { english: "by / with / of", russian: "у" },
  { english: "you / thou", russian: "ты" },
  { english: "from / of / in", russian: "из" },
  { english: "we", russian: "мы" },
  { english: "behind / over / at / after", russian: "за" },
  { english: "you (formal)", russian: "вы" },
  { english: "so / thus / then", russian: "так" },
  { english: "and / as for / but / same", russian: "же" },
  { english: "from / of / for", russian: "от" },
  { english: "to say / to speak", russian: "сказать" },
  { english: "this", russian: "этот" },
  { english: "which / who / that", russian: "который" },
  { english: "be able", russian: "мочь" },
  { english: "man / person", russian: "человек" },
  { english: "of / about / against", russian: "о" },
  { english: "one / some / alone", russian: "один" },
  { english: "still / yet", russian: "ещё" },
  { english: "would", russian: "бы" },
  { english: "such / so / some", russian: "такой" },
  { english: "only / merely / but", russian: "только" },
  { english: "myself / himself / herself", russian: "себя" },
  { english: "one's own / my / our", russian: "своё" },
  { english: "what / which / how", russian: "какой" },
  { english: "when / while / as", russian: "когда" },
  { english: "already / by now", russian: "уже" },
  { english: "for / to", russian: "для" },
  { english: "here / there / this is / that's", russian: "вот" },
  { english: "who / that / some", russian: "кто" },
  { english: "yes / but", russian: "да" },
  { english: "to say / to tell / to speak", russian: "говорить" },
  { english: "year", russian: "год" },
  { english: "to know / be aware", russian: "знать" },
  { english: "my / mine", russian: "мой" },
  { english: "to / up to / about / before", russian: "до" },
  { english: "or", russian: "или" },
  { english: "if", russian: "если" },
  { english: "time / season", russian: "время" },
  { english: "hand / arm", russian: "рука" },
  { english: "no / not / but", russian: "нет" },
  { english: "most / the very / the same", russian: "самый " },
  { english: "not a / not / neither… nor", russian: "ни" },
  { english: "to become / begin / come", russian: "стать" },
  { english: "big / large / important", russian: "большой" },
  { english: "even", russian: "даже" },
  { english: "other / another / different", russian: "другой" },
  { english: "our / ours", russian: "наш" },
  { english: "my / our / your", russian: "свой" },
  { english: "now / right / well / come on", russian: "ну" },
  { english: "under / for / towards / to", russian: "под" },
  { english: "where", russian: "где" },
  { english: "business / affair / matter", russian: "дело" },
  { english: "to eat / to be", russian: "есть" },
  { english: "myself / yourself", russian: "сам" },
  { english: "time / once / since", russian: "раз" },
  { english: "that / in order that", russian: "чтобы" },
  { english: "two", russian: "два" },
  { english: "there / then", russian: "там" },
  { english: "than / instead of", russian: "чем" },
  { english: "eye / sight", russian: "глаз" },
  { english: "life", russian: "жизнь" },
  { english: "first / front / former", russian: "первый" },
  { english: "day", russian: "день" },
  { english: "here / now / then", russian: "тут" },
  { english: "in / at / super / exactly", russian: "во" },
  { english: "nothing", russian: "ничто" },
  { english: "afterwards / then", russian: "потом" },
  { english: "very", russian: "очень" },
  { english: "with", russian: "со" },
  { english: "to want / like", russian: "хотеть" },
  { english: "whether / if", russian: "ли" },
  { english: "attached to / in the presence of / by / about", russian: "при" },
  { english: "head / mind / brains", russian: "голова" },
  { english: "over / above / ought to", russian: "надо" },
  { english: "without", russian: "без" },
  { english: "to see", russian: "видеть" },
  { english: "to go / come", russian: "идти" },
  { english: "now / nowadays", russian: "теперь" },
  { english: "also / as well / too", russian: "тоже" },
  { english: "to stand / be / stand up", russian: "стоять" },
  { english: "friend", russian: "друг" },
  { english: "house / home", russian: "дом" },
  { english: "now / presently / soon", russian: "сейчас" },
  { english: "one can", russian: "можно" },
  { english: "after / afterwards", russian: "после" },
  { english: "word", russian: "слово" },
  { english: "here", russian: "здесь" },
  { english: "to think / believe", russian: "думать" },
  { english: "place / seat", russian: "место" },
  { english: "to ask", russian: "спросить" },
  { english: "through / across", russian: "через" },
  { english: "face / person", russian: "лицо" },
  { english: "what / which / that", russian: "что" },
  { english: "then", russian: "тогда" },
  { english: "you see / you know", russian: "ведь" },
  { english: "good / nice", russian: "хороший" },
  { english: "each / every", russian: "каждый" },
  { english: "new / modern", russian: "новый" },
  { english: "to live", russian: "жить" },
  { english: "due / proper", russian: "должный" },
  { english: "to look / watch", russian: "смотреть" },
  { english: "why", russian: "почему" },
  { english: "that's why", russian: "потому" },
  { english: "side / party", russian: "сторона" },
  { english: "simply", russian: "просто" },
  { english: "foot / leg", russian: "нога" },
  { english: "to sit", russian: "сидеть" },
  { english: "to understand / realize", russian: "понять" },
  { english: "to have / own", russian: "иметь" },
  { english: "final / last", russian: "конечный" },
  { english: "to do / make", russian: "делать" },
  { english: "suddenly", russian: "вдруг" },
  { english: "above / over", russian: "над" },
  { english: "to take", russian: "взять" },
  { english: "nobody", russian: "никто" },
  { english: "to do / make / finish", russian: "сделать" },
  { english: "door", russian: "дверь" },
  { english: "before / in front of", russian: "перед" },
  { english: "necessary", russian: "нужный" },
  { english: "to understand", russian: "понимать" },
  { english: "to seem / appear", russian: "казаться" },
  { english: "work / job", russian: "работа" },
  { english: "three", russian: "три" },
  { english: "yours", russian: "ваш" },
  { english: "really / already", russian: "уж" },
  { english: "earth / land / soil", russian: "земля" },
  { english: "end / distance", russian: "конец" },
  { english: "several / some", russian: "несколько" },
  { english: "hour / time", russian: "час" },
  { english: "voice", russian: "голос" },
  { english: "town / city", russian: "город" },
  { english: "last / the latest / new", russian: "последний" },
  { english: "in / at", russian: "пока" },
  { english: "well", russian: "хорошо" },
  { english: "to give / let / allow", russian: "давать" },
  { english: "water", russian: "вода" },
  { english: "more", russian: "более" },
  { english: "although", russian: "хотя" },
  { english: "always", russian: "всегда" },
  { english: "second", russian: "второй" },
  { english: "where / what for / much", russian: "куда" },
  { english: "to go", russian: "пойти" },
  { english: "table / desk / board", russian: "стол" },
  { english: "child / kid / infant", russian: "ребёнок" },
  { english: "to see", russian: "увидеть" },
  { english: "strength / force", russian: "сила" },
  { english: "father", russian: "отец" },
  { english: "woman", russian: "женщина" },
  { english: "car / machine / engine", russian: "машина" },
  { english: "case / occasion / incident", russian: "случай" },
  { english: "night", russian: "ночь" },
  { english: "at once / right away / just", russian: "сразу" },
  { english: "world / peace", russian: "мир" },
  { english: "quite / entirely / totally", russian: "совсем" },
  { english: "to remain / stay", russian: "остаться" },
  { english: "about / of", russian: "об" },
  { english: "appearance / look / view", russian: "вид" },
  { english: "to go out / come out / appear", russian: "выйти" },
  { english: "to give", russian: "дать" },
  { english: "to work", russian: "работать" },
  { english: "to love", russian: "любить" },
  { english: "old", russian: "старый" },
  { english: "almost", russian: "почти" },
  { english: "row / line", russian: "ряд" },
  { english: "find oneself / turn out", russian: "оказаться" },
  { english: "beginning / origin / source", russian: "начало" },
  { english: "your / yours (informal)", russian: "твой" },
  { english: "question / matter / problem", russian: "вопрос" },
  { english: "many / much", russian: "много" },
  { english: "war", russian: "война" },
  { english: "again", russian: "снова" },
  { english: "to answer / reply", russian: "ответить" },
  { english: "between / among", russian: "между" },
  { english: "to think", russian: "подумать" },
  { english: "again", russian: "опять" },
  { english: "white", russian: "белый" },
  { english: "money", russian: "деньги" },
  { english: "to mean / signify", russian: "значить" },
  { english: "about / for", russian: "про" },
  { english: "only / as soon as", russian: "лишь" },
  { english: "minute / moment", russian: "минута" },
  { english: "wife", russian: "жена" },
  { english: "to take a look / watch / inspect", russian: "посмотреть" },
  { english: "truth", russian: "правда" },
  { english: "main / chief", russian: "главный" },
  { english: "country", russian: "страна" },
  { english: "light / world", russian: "свет" },
  { english: "to wait", russian: "ждать" },
  { english: "mother", russian: "мать" },
  { english: "as if / as though", russian: "будто" },
  { english: "never", russian: "никогда" },
  { english: "comrade / friend", russian: "товарищ" },
  { english: "road / way / journey", russian: "дорога" },
  { english: "however / though", russian: "однако" },
  { english: "to lie / be situated", russian: "лежать" },
  { english: "namely / just", russian: "именно" },
  { english: "window / windowsill", russian: "окно" },
  { english: "no / none", russian: "никакой" },
  { english: "to find / discover / consider", russian: "найти" },
  { english: "to write", russian: "писать" },
  { english: "a room", russian: "комната" },
  { english: "Moscow", russian: "Москва" },
  { english: "part / share / department", russian: "часть" },
  { english: "in general / altogether / on the whole", russian: "вообще" },
  { english: "a book", russian: "книга" },
  { english: "small / little", russian: "маленький" },
  { english: "street", russian: "улица" },
  { english: "to decide / solve", russian: "решить" },
  { english: "distant / remote", russian: "далекий" },
  { english: "soul / spirit", russian: "душа" },
  { english: "hardly / slightly", russian: "чуть" },
  { english: "to return", russian: "вернуться" },
  { english: "morning", russian: "утро" },
  { english: "some", russian: "некоторый" },
  { english: "to count / consider", russian: "считать" },
  { english: "how much / how many", russian: "сколько" },
  { english: "to remember", russian: "помнить" },
  { english: "evening", russian: "вечер" },
  { english: "floor / sex", russian: "пол" },
  { english: "after all", russian: "таки" },
  { english: "to receive / get / obtain", russian: "получить" },
  { english: "people / nation", russian: "народ" },
  { english: "shoulder / upper arm", russian: "плечо" },
  { english: "even / if you want / though", russian: "хоть" },
  { english: "today", russian: "сегодня" },
  { english: "god", russian: "бог" },
  { english: "together", russian: "вместе" },
  { english: "look / glance / view", russian: "взгляд" },
  { english: "to go / walk", russian: "ходить" },
  { english: "what for / why", russian: "зачем" },
  { english: "Soviet", russian: "советский" },
  { english: "russian", russian: "русский" },
  { english: "be / visit / happen", russian: "бывать" },
  { english: "full / complete", russian: "полный" },
  { english: "to come / arrive", russian: "прийти" },
  { english: "finger / toe", russian: "палец" },
  { english: "russia", russian: "Россия" },
  { english: "any / every", russian: "любой" },
  { english: "history / story / event", russian: "история" },
  { english: "at last / finally", russian: "наконец" },
  { english: "thought / idea", russian: "мысль" },
  { english: "to know / learn / recognize", russian: "узнать" },
  { english: "back / backwards", russian: "назад" },
  { english: "general / common", russian: "общий" },
  { english: "to notice / observe", russian: "заметить" },
  { english: "as if / like", russian: "словно" },
  { english: "past", russian: "прошлый" },
  { english: "to leave / go away", russian: "уйти" },
  { english: "well-known / famous", russian: "известный" },
  { english: "long ago", russian: "давно" },
  { english: "to hear", russian: "слышать" },
  { english: "to listen / hear", russian: "слушать" },
  { english: "to be afraid / fear", russian: "бояться" },
  { english: "son", russian: "сын" },
  { english: "it is impossible / can't", russian: "нельзя" },
  { english: "straight / frankly", russian: "прямо" },
  { english: "for a long time", russian: "долго" },
  { english: "fast / quickly", russian: "быстро" },
  { english: "forest", russian: "лес" },
  { english: "similar / alike", russian: "похожий" },
  { english: "time / pore", russian: "пора" },
  { english: "five", russian: "пять" },
  { english: "to look / gaze", russian: "глядеть" },
  { english: "it", russian: "оно" },
  { english: "to sit", russian: "сесть" },
  { english: "name", russian: "имя" },
  { english: "and / as for / but ", russian: "ж" },
  { english: "talk / conversation", russian: "разговор" },
  { english: "body", russian: "тело" },
  { english: "young / bridegroom (as a noun", russian: "молодой" },
  { english: "wall", russian: "стена" },
  { english: "red", russian: "красный" },
  { english: "to read", russian: "читать" },
  { english: "right", russian: "право" },
  { english: "old man", russian: "старик" },
  { english: "early", russian: "ранний" },
  { english: "want / like", russian: "хотеться" },
  { english: "mummy / mum", russian: "мама" },
  { english: "to remain / stay ", russian: "оставаться" },
  { english: "tall / high", russian: "высокий" },
  { english: "way / track / path", russian: "путь" },
  { english: "therefore", russian: "поэтому" },
  { english: "absolutely / quite", russian: "совершенно" },
  { english: "except / besides", russian: "кроме" },
  { english: "a thousand", russian: "тысяча" },
  { english: "month", russian: "месяц" },
  { english: "to take / hire", russian: "брать" },
  { english: "to write", russian: "написать" },
  { english: "intact / whole / entire", russian: "целый" },
  { english: "huge / enormous", russian: "огромный" },
  { english: "to begin ", russian: "начинать" },
  { english: "back", russian: "спина" },
  { english: "present / real / true", russian: "настоящий" },
  { english: "let's / though", russian: "пусть" },
  { english: "tongue / language", russian: "язык" },
  { english: "exactly", russian: "точно" },
  { english: "among", russian: "среди" },
  { english: "to feel", russian: "чувствовать" },
  { english: "heart", russian: "сердце" },
  { english: "to lead", russian: "вести" },
  { english: "sometimes", russian: "иногда" },
  { english: "boy", russian: "мальчик" },
  { english: "to be in time / be successful", russian: "успеть" },
  { english: "sky", russian: "небо" },
  { english: "living / live / lively", russian: "живой" },
  { english: "death", russian: "смерть" },
  { english: "to continue", russian: "продолжать" },
  { english: "girl / miss ", russian: "девушка" },
  { english: "shape / form / image", russian: "образ" },
  { english: "to / towards / by ", russian: "ко" },
  { english: "to forget", russian: "забыть" },
  { english: "around", russian: "вокруг" },
  { english: "letter", russian: "письмо" },
  { english: "power", russian: "власть" },
  { english: "black ", russian: "чёрный" },
  { english: "to pass / go by / be over ", russian: "пройти" },
  { english: "to appear / show up ", russian: "появиться" },
  { english: "air", russian: "воздух" },
  { english: "different", russian: "разный" },
  { english: "to go out / nurse ", russian: "выходить" },
  { english: "to ask", russian: "просить" },
  { english: "brother", russian: "брат" },
  { english: "one's own", russian: "собственный" },
  { english: "relationship / attitude", russian: "отношение" },
  { english: "then / after that", russian: "затем" },
  { english: "to try", russian: "пытаться" },
  { english: "to show / display", russian: "показать" },
  { english: "to remember / recall", russian: "вспомнить" },
  { english: "system", russian: "система" },
  { english: "four", russian: "четыре" },
  { english: "flat / apartment", russian: "квартира" },
  { english: "to hold / keep", russian: "держать" },
  { english: "also / as well / too", russian: "также" },
  { english: "love", russian: "любовь" },
  { english: "soldier", russian: "солдат" },
  { english: "where… from", russian: "откуда" },
  { english: "that / in order that", russian: "чтоб" },
  { english: "to call / name", russian: "называть" },
  { english: "third", russian: "третий" },
  { english: "master / boss / host", russian: "хозяин" },
  { english: "like / not unlike", russian: "вроде" },
  { english: "to leave / go away", russian: "уходить" },
  { english: "to approach / come up", russian: "подойти" },
  { english: "to lift / raise", russian: "поднять" },
  { english: "especially / particularly", russian: "особенно" },
  { english: "to ask / inquire", russian: "спрашивать" },
  { english: "chief / head / superior", russian: "начальник" },
  { english: "both", russian: "оба" },
  { english: "to throw", russian: "бросить" },
  { english: "school", russian: "школа" },
  { english: "boy / fellow / guy", russian: "парень" },
  { english: "blood", russian: "кровь" },
  { english: "twenty", russian: "двадцать" },
  { english: "sun", russian: "солнце" },
  { english: "week", russian: "неделя" },
  { english: "to send / dispatch", russian: "послать" },
  { english: "to be found / turn up", russian: "находиться" },
  { english: "guys / children", russian: "ребята" },
  { english: "to put / place / set", russian: "поставить" },
  { english: "to get up / rise / stand up", russian: "встать" },
  { english: "for example / for instance", russian: "например" },
  { english: "step", russian: "шаг" },
  { english: "man / male", russian: "мужчина" },
  { english: "alike / in like manner", russian: "равно" },
  { english: "nose", russian: "нос" },
  { english: "little / few", russian: "мало" },
  { english: "attention", russian: "внимание" },
  { english: "captain / master", russian: "капитан" },
  { english: "ear", russian: "ухо" },
  { english: "there", russian: "туда" },
  { english: "here", russian: "сюда" },
  { english: "to play", russian: "играть" },
  { english: "to follow / come next", russian: "следовать" },
  { english: "to tell / narrate", russian: "рассказать" },
  { english: "great", russian: "великий" },
  { english: "indeed / really", russian: "действительно" },
  { english: "too / too much", russian: "слишком" },
  { english: "heavy", russian: "тяжёлый" },
  { english: "to sleep", russian: "спать" },
  { english: "to leave / abandon", russian: "оставить" },
  { english: "to enter / come in", russian: "войти" },
  { english: "long", russian: "длинный" },
  { english: "feeling", russian: "чувство" },
  { english: "to keep silence", russian: "молчать" },
  { english: "to tell / narrate", russian: "рассказывать" },
  { english: "to answer / reply", russian: "отвечать" },
  { english: "to stand / to become", russian: "становиться" },
  { english: "to stop", russian: "остановиться" },
  { english: "bank / shore / coast", russian: "берег" },
  { english: "family", russian: "семья" },
  { english: "to search", russian: "искать" },
  { english: "general", russian: "генерал" },
  { english: "moment / instant", russian: "момент" },
  { english: "ten", russian: "десять" },
  { english: "to begin", russian: "начать" },
  { english: "next / following", russian: "следующий" },
  { english: "personal", russian: "личный" },
  { english: "labour / work", russian: "труд" },
  { english: "to believe", russian: "верить" },
  { english: "group", russian: "группа" },
  { english: "a little", russian: "немного" },
  { english: "however / though", russian: "впрочем" },
  { english: "evidently / obviously", russian: "видно" },
  { english: "to appear", russian: "являться" },
  { english: "husband", russian: "муж" },
  { english: "really? / perhaps", russian: "разве" },
  { english: "movement", russian: "движение" },
  { english: "order", russian: "порядок" },
  { english: "answer / reply", russian: "ответ" },
  { english: "quietly / softly / slowly", russian: "тихо" },
  { english: "familiar / acquainted", russian: "знакомый" },
  { english: "newspaper", russian: "газета" },
  { english: "help", russian: "помощь" },
  { english: "strong / powerful", russian: "сильный" },
  { english: "quick / fast", russian: "скорый" },
  { english: "dog", russian: "собака" },
  { english: "tree", russian: "дерево" },
  { english: "snow", russian: "снег" },
  { english: "dream", russian: "сон" },
  { english: "sense / meaning / purpose", russian: "смысл" },
  { english: "to be able", russian: "смочь" },
  { english: "against / opposite / contrary to", russian: "против" },
  { english: "to run / hurry", russian: "бежать" },
  { english: "yard / court", russian: "двор" },
  { english: "form / shape / uniform", russian: "форма" },
  { english: "simple / easy / plain", russian: "простой" },
  { english: "to arrive / come", russian: "приехать" },
  { english: "different / other", russian: "иной" },
  { english: "to cry / shout", russian: "кричать" },
  { english: "possibility / opportunity / chance", russian: "возможность" },
  { english: "society", russian: "общество" },
  { english: "green", russian: "зеленый" },
  { english: "breast / chest", russian: "грудь" },
  { english: "corner / angle", russian: "угол" },
  { english: "to open", russian: "открыть" },
  { english: "to happen / occur / take place", russian: "происходить" },
  { english: "in harmony / well / all right", russian: "ладно" },
  { english: "black", russian: "черный" },
  { english: "century / age", russian: "век" },
  { english: "pocket", russian: "карман" },
  { english: "to go / ride / drive / travel", russian: "ехать" },
  { english: "German", russian: "немец" },
  { english: "probably / most likely", russian: "наверное" },
  { english: "lip", russian: "губа" },
  { english: "uncle", russian: "дядя" },
  { english: "to come / arrive", russian: "приходить" },
  { english: "often", russian: "часто" },
  { english: "home", russian: "домой" },
  { english: "fire", russian: "огонь" },
  { english: "writer", russian: "писатель" },
  { english: "army", russian: "армия" },
  { english: "state / condition / fortune", russian: "состояние" },
  { english: "tooth", russian: "зуб" },
  { english: "line / queue / turn", russian: "очередь" },
  {
    english: "which (old-fashioned",
    russian: "кой",
  },
  { english: "to rise / climb", russian: "подняться" },
  { english: "stone", russian: "камень" },
  { english: "guest", russian: "гость" },
  { english: "to appear / come in sight", russian: "показаться" },
  { english: "wind", russian: "ветер" },
  {
    english: "to gather together / assemble",
    russian: "собираться",
  },
  { english: "to hit / to find oneself", russian: "попасть" },
  { english: "to take / admit / accept", russian: "принять" },
  { english: "at first / from the beginning", russian: "сначала" },
  { english: "or", russian: "либо" },
  { english: "to depart / set off", russian: "поехать" },
  { english: "to hear", russian: "услышать" },
  { english: "to be able / know / can", russian: "уметь" },
  { english: "to happen", russian: "случиться" },
  { english: "strange", russian: "странный" },
  { english: "only / sole", russian: "единственный" },
  { english: "company (military", russian: "рота" },
  { english: "law / act / statue", russian: "закон" },
  { english: "short", russian: "короткий" },
  { english: "sea", russian: "море" },
  { english: "kind", russian: "добрый" },
  { english: "dark", russian: "темный" },
  { english: "mountain / hill", russian: "гора" },
  { english: "physician / doctor", russian: "врач" },
  { english: "border / edge / land / country", russian: "край" },
  { english: "to try / endeavour", russian: "стараться" },
  { english: "better / best", russian: "лучший" },
  { english: "river", russian: "река" },
  { english: "military", russian: "военный" },
  { english: "measure / step", russian: "мера" },
  { english: "terrible / frightful", russian: "страшный" },
  { english: "quite / fully", russian: "вполне" },
  { english: "to call", russian: "звать" },
  { english: "to happen / occur / take place", russian: "произойти" },
  { english: "forward", russian: "вперед" },
  { english: "slowly", russian: "медленно" },
  { english: "by / near / close by", russian: "возле" },
  { english: "in now way / by no means", russian: "никак" },
  { english: "to be occupied / engage", russian: "заниматься" },
  { english: "action / effect", russian: "действие" },
  { english: "enough / rather", russian: "довольно" },
  { english: "thing", russian: "вещь" },
  { english: "necessary", russian: "необходимый" },
  { english: "move", russian: "ход" },
  { english: "pain", russian: "боль" },
  { english: "fate / fortune / destiny", russian: "судьба" },
  { english: "cause / reason / motive", russian: "причина" },
  { english: "to lay down / put down / place", russian: "положить" },
  { english: "hardly / just / barely", russian: "едва" },
  { english: "line / boundary / trait", russian: "черта" },
  { english: "girl / little girl", russian: "девочка" },
  { english: "light / easy", russian: "лёгкий" },
  { english: "hair", russian: "волос" },
  { english: "to buy / purchase", russian: "купить" },
  { english: "number / size / room / issue", russian: "номер" },
  { english: "main", russian: "основной" },
  { english: "wide", russian: "широкий" },
  { english: "to die", russian: "умереть" },
  { english: "far / far off", russian: "далеко" },
  { english: "badly", russian: "плохо" },
  { english: "head / chief", russian: "глава" },
  { english: "beautiful", russian: "красивый" },
  { english: "grey / dull", russian: "серый" },
  { english: "to drink", russian: "пить" },
  { english: "commander / commanding officer", russian: "командир" },
  { english: "usually", russian: "обычно" },
  { english: "party", russian: "партия" },
  { english: "problem / issue", russian: "проблема" },
  { english: "fear", russian: "страх" },
  { english: "to pass / go / study", russian: "проходить" },
  { english: "clear / clearly", russian: "ясно" },
  { english: "to take away / take off / photograph", russian: "снять" },
  { english: "paper", russian: "бумага" },
  { english: "hero", russian: "герой" },
  { english: "pair / couple", russian: "пара" },
  { english: "State", russian: "государство" },
  { english: "village / country", russian: "деревня" },
  { english: "speech", russian: "речь" },
  { english: "to begin", russian: "начаться" },
  { english: "means / remedy", russian: "средство" },
  { english: "position / posture / condition / state", russian: "положение" },
  { english: "tie / bond / connection / relation", russian: "связь" },
  { english: "quickly / fast / soon", russian: "скоро" },
  { english: "small / not great", russian: "небольшой" },
  {
    english: "to present / introduce / imagine",
    russian: "представлять",
  },
  { english: "tomorrow", russian: "завтра" },
  { english: "to explain", russian: "объяснить" },
  { english: "empty / hollow / idle", russian: "пустой" },
  { english: "to pronounce / say / utter", russian: "произнести" },
  { english: "human", russian: "человеческий" },
  { english: "to please / like", russian: "нравиться" },
  { english: "once / one day", russian: "однажды" },
  { english: "past / by", russian: "мимо" },
  { english: "otherwise / differentlyl", russian: "иначе" },
  { english: "to exist / to be", russian: "существовать" },
  { english: "class", russian: "класс" },
  { english: "turn out well / succeed / manage", russian: "удаться" },
  { english: "thick / heavy / fat", russian: "толстый" },
  { english: "goal / object / target", russian: "цель" },
  { english: "through", russian: "сквозь" },
  { english: "to fit / fall / have to", russian: "прийтись" },
  { english: "clean / pure", russian: "чистый" },
  { english: "to know", russian: "знать" },
  { english: "former", russian: "прежний" },
  { english: "professor", russian: "профессор" },
  { english: "gentleman / Mr.", russian: "господин" },
  { english: "happiness / luck", russian: "счастье" },
  { english: "thin / skinny", russian: "худой" },
  { english: "spirit", russian: "дух" },
  { english: "plan", russian: "план" },
  { english: "somebody else's / strange / foreign", russian: "чужой" },
  { english: "hall", russian: "зал" },
  { english: "to presetn / produce / introduce", russian: "представить" },
  { english: "special", russian: "особый" },
  { english: "director / manager", russian: "директор" },
  { english: "former / ex-", russian: "бывший" },
  { english: "memory", russian: "память" },
  { english: "near / similar / intimate", russian: "близкий" },
  { english: "this", russian: "сей" },
  { english: "result / outcome", russian: "результат" },
  { english: "sick", russian: "больной" },
  { english: "given / present", russian: "данный" },
  { english: "to the point / at the same time", russian: "кстати" },
  { english: "to call / name", russian: "назвать" },
  { english: "track / footprint", russian: "след" },
  { english: "to smile", russian: "улыбаться" },
  { english: "bottle", russian: "бутылка" },
  { english: "with difficulty", russian: "трудно" },
  { english: "condition / term", russian: "условие" },
  { english: "before", russian: "прежде" },
  { english: "mind / brains / intellect", russian: "ум" },
  { english: "to smile", russian: "улыбнуться" },
  { english: "process", russian: "процесс" },
  { english: "picture / painting", russian: "картина" },
  { english: "instead", russian: "вместо" },
  { english: "elder / senior", russian: "старший" },
  { english: "easily / lightly", russian: "легко" },
  { english: "center", russian: "центр" },
  { english: "similar / like", russian: "подобный" },
  { english: "as… as possible", russian: "возможно" },
  { english: "by / near", russian: "около" },
  { english: "to laugh", russian: "смеяться" },
  { english: "hundred", russian: "сто" },
  { english: "future", russian: "будущее" },
  { english: "to snatch / seize / be sufficient", russian: "хватать" },
  { english: "number", russian: "число" },
  { english: "any / every", russian: "всякое" },
  { english: "ruble", russian: "рубль" },
  { english: "to feel", russian: "почувствовать" },
  { english: "to bring", russian: "принести" },
  { english: "faith / belief", russian: "вера" },
  { english: "quiet / not … at all", russian: "вовсе" },
  { english: "blow / stroke", russian: "удар" },
  { english: "telephone", russian: "телефон" },
  { english: "knee", russian: "колено" },
  { english: "to agree / consent", russian: "согласиться" },
  { english: "little / few / not enough", russian: "мало" },
  { english: "corridor / passage", russian: "коридор" },
  { english: "music", russian: "мужик" },
  { english: "right", russian: "правый" },
  { english: "author", russian: "автор" },
  { english: "cold / cool", russian: "холодный" },
  { english: "to snatch / seize / suffice", russian: "хватить" },
  { english: "many", russian: "многие" },
  { english: "meeting / reception", russian: "встреча" },
  { english: "study / room / office suite", russian: "кабинет" },
  { english: "document", russian: "документ" },
  { english: "aircraft / aeroplane", russian: "самолет" },
  { english: "down / downwards", russian: "вниз" },
  { english: "to take / admit / accept ", russian: "принимать" },
  { english: "game / play", russian: "игра" },
  { english: "story", russian: "рассказ" },
  { english: "bread", russian: "хлеб" },
  { english: "development", russian: "развитие" },
  { english: "to kill", russian: "убить" },
  { english: "own / native / dear", russian: "родной" },
  { english: "open", russian: "открытый" },
  { english: "less", russian: "менее" },
  { english: "to offer / propose / suggest", russian: "предложить" },
  { english: "yellow", russian: "желтый" },
  { english: "to fit / fall / have to", russian: "приходиться" },
  { english: "to drink", russian: "выпить" },
  { english: "to cry / shout", russian: "крикнуть" },
  { english: "tube / roll / pipe", russian: "трубка" },
  { english: "enemy", russian: "враг" },
  { english: "to show / display", russian: "показывать" },
  { english: "two", russian: "двое" },
  { english: "doctor", russian: "доктор" },
  { english: "palm", russian: "ладонь" },
  { english: "to call / send", russian: "вызвать" },
  { english: "quietly", russian: "спокойно" },
  { english: "to ask", russian: "попросить" },
  { english: "science", russian: "наука" },
  { english: "lieutenant", russian: "лейтенант" },
  { english: "service / work", russian: "служба" },
  { english: "to turn out / find oneself", russian: "оказываться" },
  { english: "to bring", russian: "привести" },
  { english: "forty", russian: "сорок" },
  { english: "bill / account", russian: "счет" },
  { english: "to return", russian: "возвращаться" },
  { english: "golden", russian: "золотой" },
  { english: "local", russian: "местный" },
  { english: "kitchen", russian: "кухня" },
  { english: "large / big / prominent", russian: "крупный" },
  { english: "decision / conclusion", russian: "решение" },
  { english: "bride / young", russian: "молодая" },
  { english: "thirty", russian: "тридцать" },
  { english: "novel / romance", russian: "роман" },
  { english: "to demand", russian: "требовать" },
  { english: "company", russian: "компания" },
  { english: "frequent", russian: "частый" },
  { english: "russian", russian: "российский" },
  { english: "working", russian: "рабочий" },
  { english: "to lose", russian: "потерять" },
  { english: "current", russian: "течение" },
  { english: "dark blue", russian: "синий" },
  { english: "so much / so many", russian: "столько" },
  { english: "warm", russian: "теплый" },
  { english: "meter / metre", russian: "метр" },
  { english: "to reach / get / obtain", russian: "достать" },
  { english: "ferreous / iron", russian: "железный" },
  { english: "institute", russian: "институт" },
  { english: "to report / let know", russian: "сообщить" },
  { english: "interes", russian: "интерес" },
  { english: "usual / ordinary", russian: "обычный" },
  { english: "to appear / show up", russian: "появляться" },
  { english: "to fall", russian: "упасть" },
  { english: "remaining / the rest of", russian: "остальной" },
  { english: "half", russian: "половина" },
  { english: "Moscow", russian: "московский" },
  { english: "six", russian: "шесть" },
  { english: "to come / arrive / turn out", russian: "получиться" },
  { english: "quality", russian: "качество" },
  { english: "battle / fight / combat", russian: "бой" },
  { english: "neck", russian: "шея" },
  { english: "out", russian: "вон" },
  { english: "idea", russian: "идея" },
  { english: "apparently / seemingly", russian: "видимо" },
  { english: "enough / sufficiently", russian: "достаточно" },
  {
    english: "to accompany / set off / conduct / spend ",
    russian: "провести",
  },
  { english: "important", russian: "важный" },
  { english: "grass", russian: "трава" },
  { english: "grandfather / old man", russian: "дед" },
  { english: "consciousness", russian: "сознание" },
  { english: "parent", russian: "родитель" },
  { english: "to forgive", russian: "простить" },
  { english: "to beat / hit", russian: "бить" },
  { english: "tea", russian: "чай" },
  { english: "late", russian: "поздний" },
  { english: "to nod", russian: "кивнуть" },
  { english: "family / clan / generation", russian: "род" },
  { english: "to disappear", russian: "исчезнуть" },
  { english: "thin", russian: "тонкий" },
  { english: "German", russian: "немецкий" },
  { english: "sound", russian: "звук" },
  { english: "to return / give back", russian: "отдать" },
  { english: "shop / store", russian: "магазин" },
  { english: "presidentdirector", russian: "президент" },
  { english: "poet", russian: "поэт" },
  { english: "gratitude / thanks", russian: "спасибо" },
  { english: "illness / sickness / disease", russian: "болезнь" },
  { english: "event", russian: "событие" },
  { english: "to help ", russian: "помочь" },
  { english: "skin", russian: "кожа" },
  { english: "leaf / sheet", russian: "лист" },
  { english: "to send", russian: "слать" },
  { english: "to remember / recall", russian: "вспоминать" },
  { english: "beautiful / fine", russian: "прекрасный" },
  { english: "tear", russian: "слеза" },
  { english: "hope", russian: "надежда" },
  { english: "silently / without a word", russian: "молча" },
  { english: "strongly", russian: "сильно" },
  { english: "correctfaithfulreliable", russian: "верный" },
  { english: "literature", russian: "литература" },
  { english: "weapon", russian: "оружие" },
  { english: "ready", russian: "готовый" },
  { english: "smell / odour / scent", russian: "запах" },
  { english: "unexpectedly / suddenly", russian: "неожиданно" },
  { english: "yesterday", russian: "вчера" },
  { english: "to take breath / to sigh", russian: "вздохнуть" },
  { english: "role", russian: "роль" },
  { english: "growth / increaseheight", russian: "рост" },
  { english: "nature", russian: "природа" },
  { english: "political", russian: "политический" },
  { english: "dot / point", russian: "точка" },
  { english: "star", russian: "звезда" },
  { english: "to sing", russian: "петь" },
  { english: "to sit down", russian: "садиться" },
  { english: "surname", russian: "фамилия" },
  { english: "character / disposition / temper", russian: "характер" },
  { english: "please", russian: "пожалуйста" },
  { english: "higher", russian: "выше" },
  { english: "officer", russian: "офицер" },
  { english: "crowd", russian: "толпа" },
  { english: "to stop / cease", russian: "перестать" },
  { english: "to fit / fallhave to", russian: "придтись" },
  { english: "level", russian: "уровень" },
  { english: "unknown", russian: "неизвестный" },
  { english: "armchair", russian: "кресло" },
  { english: "woman / wife / old woman", russian: "баба" },
  { english: "a second", russian: "секунда" },
  { english: "to grant / bestow", russian: "пожаловать" },
  { english: "bank", russian: "банк" },
  { english: "experience", russian: "опыт" },
  { english: "quiet / low / scelent", russian: "тихий" },
  { english: "so far as / since", russian: "поскольку" },
  { english: "high boot", russian: "сапог" },
  { english: "rule", russian: "правило" },
  { english: "glass", russian: "стекло" },
  { english: "to receive / get ", russian: "получать" },
  { english: "inside / internal", russian: "внутренний" },
  { english: "daughter", russian: "дочь" },
  { english: "to call oneself", russian: "называться" },
  { english: "to hope", russian: "надеяться" },
  { english: "member / limb", russian: "член" },
  { english: "to stretch / extend", russian: "протянуть" },
  { english: "State", russian: "государственный" },
  { english: "ten / dozens", russian: "десяток" },
  { english: "deep", russian: "глубокий" },
  { english: "flower", russian: "цветок" },
  { english: "ah! / oh!", russian: "ах" },
  { english: "wish", russian: "желание" },
  { english: "rain", russian: "дождь" },
  { english: "before / in front of", russian: "впереди" },
  { english: "to come up / approach / to fit", russian: "подходить" },
  { english: "many / much / a lot of", russian: "много" },
  { english: "forehead", russian: "лоб" },
  { english: "smile", russian: "улыбка" },
  { english: "fight / struggle", russian: "борьба" },
  { english: "collar", russian: "ворот" },
  { english: "box / case", russian: "ящик" },
  { english: "floor / storey", russian: "этаж" },
  { english: "to serve", russian: "служить" },
  { english: "again / once more", russian: "вновь" },
  { english: "blue / sky-blue", russian: "голубой" },
  { english: "there is nothing / there is no need", russian: "нечего" },
  { english: "revolution", russian: "революция" },
  { english: "for the first time", russian: "впервые" },
  { english: "neighbour", russian: "сосед" },
  { english: "sister", russian: "сестра" },
  { english: "long", russian: "долгий" },
  { english: "whose", russian: "чей" },
  { english: "to believe", russian: "поверить" },
  { english: "situation", russian: "ситуация" },
  { english: "to look / give a glance", russian: "взглянуть" },
  { english: "weak", russian: "слабый" },
  { english: "quantity", russian: "количество" },
  { english: "to call / send", russian: "вызывать " },
  { english: "confident / sure", russian: "уверенный" },
  { english: "exit", russian: "выход" },
  { english: "advice", russian: "совет" },
  { english: "fool / idiot", russian: "дурак" },
  { english: "dear / loved", russian: "любимый" },
  { english: "union / alliance / conjunction", russian: "союз" },
  { english: "summer", russian: "лето" },
  { english: "to expect", russian: "ожидать" },
  { english: "alien / strange", russian: "пришлый" },
  { english: "to hang", russian: "висеть" },
  { english: "border", russian: "граница" },
  { english: "colour / color", russian: "цвет" },
  { english: "serious", russian: "серьезный" },
  { english: "to create / establish", russian: "создать" },
  { english: "interestingly", russian: "интересно" },
  { english: "freedom", russian: "свобода" },
  { english: "but / but then", russian: "зато" },
  { english: "chair", russian: "стул" },
  { english: "to leave / depart", russian: "уехать" },
  { english: "train", russian: "поезд" },
  { english: "music", russian: "музыка" },
  { english: "quick / fast", russian: "быстрый" },
  { english: "shadow", russian: "тень" },
  { english: "horse", russian: "лошадь" },
  { english: "field", russian: "поле" },
  { english: "to look", russian: "выглядеть" },
  { english: "to study / learn", russian: "учиться" },
  { english: "left", russian: "левый" },
  { english: "to talk / speak", russian: "разговаривать" },
  { english: "child's / children's", russian: "детский" },
  { english: "type / model", russian: "тип" },
  { english: "court / law-court", russian: "суд" },
  { english: "related / connected / tied-up", russian: "связанный" },
  { english: "hot", russian: "горячий" },
  { english: "square / area", russian: "площадь" },
  { english: "to help / assist", russian: "помогать" },
  { english: "happy", russian: "счастливый" },
  { english: "to turn", russian: "повернуться" },
  { english: "to allow / permit", russian: "позволить" },
  { english: "to meet", russian: "встретить" },
  { english: "gladness / joy", russian: "радость" },
  { english: "sharp / spicy", russian: "острый" },
  { english: "age", russian: "возраст" },
  { english: "organ / body", russian: "орган" },
  { english: "map", russian: "карта" },
  { english: "to enter / come in", russian: "входить" },
  { english: "to discover / find out", russian: "обнаружить" },
  { english: "king", russian: "король" },
  { english: "glory / fame", russian: "слава" },
  { english: "colonel", russian: "полковник" },
  { english: "shallow / small", russian: "мелкий" },
  { english: "side / flank", russian: "бок" },
  { english: "price", russian: "цена" },
  { english: "information", russian: "информация" },
  { english: "brain", russian: "мозг" },
  { english: "pleasure", russian: "удовольствие" },
  { english: "will", russian: "воля" },
  { english: "oblast / province / field", russian: "область" },
  { english: "roof", russian: "крыша" },
  { english: "to carry", russian: "нести" },
  { english: "back / backwards", russian: "обратно" },
  { english: "contemporary / modern / up-to-date", russian: "современный" },
  { english: "lady / partner / queen", russian: "дама" },
  { english: "seven", russian: "семь" },
  { english: "cheerful / merry", russian: "веселый" },
  { english: "to send", russian: "прислать" },
  { english: "garden / yard", russian: "сад" },
  { english: "government", russian: "правительство" },
  { english: "nice / sweet / dear", russian: "милый" },
  { english: "to treat / regard / relate", russian: "относиться" },
  { english: "to arise / appear", russian: "возникать" },
  { english: "he says / they say / etc.", russian: "мол" },
  { english: "to repeat", russian: "повторить" },
  { english: "name / title", russian: "название" },
  { english: "average / middle", russian: "средний" },
  { english: "example", russian: "пример" },
  { english: "impossible", russian: "невозможно" },
  { english: "mirror", russian: "зеркало" },
  { english: "to perish / be killed", russian: "погибнуть" },
  { english: "American", russian: "американский" },
  { english: "smoke", russian: "дым" },
  { english: "to burn", russian: "гореть" },
  { english: "to cry", russian: "плакать" },
  { english: "very / highly / greatly", russian: "весьма" },
  { english: "fact", russian: "факт" },
  { english: "to move", russian: "двигаться" },
  { english: "fish", russian: "рыба" },
  { english: "to add", russian: "добавить" },
  { english: "to wonder / be surprised", russian: "удивиться" },
  { english: "grandmother", russian: "бабушка" },
  { english: "wine", russian: "вино" },
  { english: "for", russian: "ибо" },
  { english: "teacher / instructor", russian: "учитель" },
  { english: "to act", russian: "действовать" },
  { english: "carefully / cautiously", russian: "осторожно" },
  { english: "circle", russian: "круг" },
  { english: "dad / daddy", russian: "папа" },
  { english: "correctly / properly", russian: "правильно" },
  { english: "recently / lately", russian: "недавно" },
  { english: "to hold on / behave", russian: "держаться" },
  { english: "moreover / and what's more", russian: "причем" },
  { english: "to fly", russian: "лететь" },
  { english: "to wear", russian: "носить" },
  { english: "occasion / reason / bridle", russian: "повод" },
  { english: "camp", russian: "лагерь" },
  { english: "bird", russian: "птица" },
  { english: "ship", russian: "корабль" },
  { english: "opinion", russian: "мнение" },
  { english: "night", russian: "ночной" },
  { english: "healthy", russian: "здоровый" },
  { english: "winter", russian: "зима" },
  { english: "dry", russian: "сухой" },
  { english: "kilometre / kilometer", russian: "километр" },
  { english: "bed", russian: "кровать" },
  { english: "to get used to / to grow accustomed to", russian: "привыкнуть" },
  { english: "et cetera / other", russian: "прочее" },
  { english: "free", russian: "свободный" },
  { english: "staircase", russian: "лестница" },
  { english: "really / surely", russian: "неужели" },
  { english: "without fail / be sure", russian: "обязательно" },
  { english: "up / upwards", russian: "вверх" },
  { english: "childhood", russian: "детство" },
  { english: "island", russian: "остров" },
  { english: "article", russian: "статья" },
  { english: "to call / to telephone", russian: "позвонить" },
  { english: "so", russian: "столь" },
  { english: "to interfere / prevent / mix", russian: "мешать" },
  { english: "vodka", russian: "водка" },
  { english: "darkness", russian: "темнота" },
  { english: "to arise / spring up", russian: "возникнуть" },
  { english: "capable (of)", russian: "способный" },
  { english: "station", russian: "станция" },
  { english: "to wish", russian: "желать" },
  { english: "to try / test", russian: "попробовать" },
  { english: "to come out", russian: "получаться" },
  { english: "citizen", russian: "гражданин" },
  { english: "strangely", russian: "странно" },
  { english: "soon / shortly", russian: "вскоре" },
  { english: "interesting", russian: "интересный" },
  { english: "team / command", russian: "команда" },
  { english: "disease / illness", russian: "заболевание" },
  { english: "stomach / belly", russian: "живот" },
  { english: "to put / place / set", russian: "ставить" },
  { english: "for the sake of", russian: "ради" },
  { english: "silence / stillness", russian: "тишина" },
  { english: "clearly / plainly", russian: "понятно" },
  { english: "front", russian: "фронт" },
  { english: "cheek", russian: "щека" },
  { english: "terribly / awfully", russian: "страшно" },
  { english: "area / region", russian: "район" },
  { english: "probably", russian: "наверно" },
  { english: "to lead / escort / accompany", russian: "проводить" },
  { english: "expression", russian: "выражение" },
  { english: "slightly", russian: "слегка" },
  { english: "bag / sack", russian: "мешок" },
  { english: "to promise", russian: "обещать" },
  { english: "on the way", russian: "дорогой" },
  { english: "to judge / try", russian: "судить" },
  { english: "majority", russian: "большинство" },
  { english: "to gather / collect", russian: "собраться" },
  { english: "operation / control", russian: "управление" },
  { english: "to prick", russian: "колоть" },
  { english: "wet", russian: "мокрый" },
  { english: "order", russian: "приказ" },
  { english: "straight", russian: "прямой" },
  { english: "to shout / cry out", russian: "закричать" },
  { english: "to end", russian: "кончиться" },
  { english: "bush", russian: "куст" },
  { english: "to shoot", russian: "стрелять" },
  { english: "painter / artist", russian: "художник" },
  { english: "sign", russian: "знак" },
  { english: "factory", russian: "завод" },
  { english: "fist", russian: "кулак" },
  { english: "to use / utilize / make use of", russian: "использовать" },
  { english: "glass", russian: "стакан" },
  { english: "to smell", russian: "пахнуть" },
  { english: "from here", russian: "отсюда" },
  { english: "mouth", russian: "рот" },
  { english: "it's time / at times / now and then", russian: "пора" },
];

function findDuplicates(array) {
  const duplicates = [];

  for (let i = 0; i < array.length - 1; i++) {
    for (let j = i + 1; j < array.length; j++) {
      if (isEqual(array[i], array[j])) {
        duplicates.push(array[i]);
        duplicates.push(array[j]);
      }
    }
  }

  return duplicates;
}

function isEqual(obj1, obj2) {
  return obj1.english === obj2.english && obj1.russian === obj2.russian;
}

const duplicatesRussian = findDuplicates(russianVocabulary);

if (duplicatesRussian.length > 0) {
  console.log("Duplicates found:");
  duplicatesRussian.forEach((duplicate) => {
    console.log(`English: ${duplicate.english}, Russian: ${duplicate.russian}`);
  });
} else {
  console.log("No duplicates found in the russian list.");
}
